### PR TITLE
Fix async word

### PR DESCRIPTION
**Pull request by ppkn**
I was going to write this fix, but it looks like @eugeneware beat me to it. I'd love to have your :eyes: @crawles 

This should fix the problem in #10

### CODE REVIEW

**Review by crawles — APPROVED** [review]
Looks good and tests passed. Thank you!

**Comment by crawles** [comment]
Let me get current owners to merge.

**Comment by scottcode** [comment]
The tests pass for me, too. I just merged it. Thanks, @dpipkin !

**Comment by jbwhit** [comment]
Has the pip version been upgraded? I installed via pip today and am still seeing the old behavior.

**Comment by crawles** [comment]
No, it needs to be added to pip.

do pip install git+git://github.com/pivotal-legacy/sql_magic for now

I will update PyPI

Chris

**Pull request merged**
